version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist/public s3://${S3_BUCKET_NAME}/ --delete
      - |
        if [ ! -z "${CLOUDFRONT_DISTRIBUTION_ID}" ]; then
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
        fi

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/public'

cache:
  paths:
    - 'node_modules/**/*'